export  const departments = [
  {
    id: 1,
    name: "Roads & Infrastructure",
    description: "Handles potholes, road damage, footpaths, bridges.",
    issues: "Potholes, Road Cracks, Broken Footpaths",
    contact: "roads@civicseva.com",
  },
  {
    id: 2,
    name: "Sanitation & Waste Management",
    description: "Garbage collection, waste disposal, cleanliness.",
    issues: "Garbage Overflow, Missed Collection, Open Dumping",
    contact: "sanitation@civicseva.com",
  },
  {
    id: 3,
    name: "Water Supply Department",
    description: "Manages water supply, leakage, and pipeline issues.",
    issues: "Water Leakage, Low Pressure, No Water Supply",
    contact: "water@civicseva.com",
  },
  {
    id: 4,
    name: "Electricity Department",
    description: "Power supply, damaged poles, meters, street power.",
    issues: "Power Cut, Damaged Pole, Faulty Meter",
    contact: "electricity@civicseva.com",
  },
  {
    id: 5,
    name: "Street Lighting Department",
    description: "Maintenance of streetlights and public lighting.",
    issues: "Street Light Not Working, Broken Poles",
    contact: "streetlights@civicseva.com",
  },
  {
    id: 6,
    name: "Drainage & Sewerage Department",
    description: "Drain cleaning, sewer overflow, wastewater issues.",
    issues: "Blocked Drains, Sewer Overflow, Bad Odour",
    contact: "drainage@civicseva.com",
  },
  {
    id: 7,
    name: "Public Health & Hygiene",
    description: "Ensures public hygiene and disease prevention.",
    issues: "Mosquito Breeding, Public Toilet Issues",
    contact: "health@civicseva.com",
  },
  {
    id: 8,
    name: "Parks & Gardens Department",
    description: "Maintenance of parks, gardens, and playgrounds.",
    issues: "Broken Benches, Overgrown Plants, Play Area Damage",
    contact: "parks@civicseva.com",
  },
  {
    id: 9,
    name: "Traffic Management Department",
    description: "Traffic signals, road congestion, parking issues.",
    issues: "Signal Not Working, Traffic Jam, Illegal Parking",
    contact: "traffic@civicseva.com",
  },
  {
    id: 10,
    name: "Public Transport Department",
    description: "Bus stops, shelters, public transport services.",
    issues: "Damaged Bus Stop, Service Delay",
    contact: "transport@civicseva.com",
  },
  {
    id: 11,
    name: "Fire & Safety Department",
    description: "Fire safety checks and emergency preparedness.",
    issues: "Fire Hazard, Blocked Fire Exit",
    contact: "firesafety@civicseva.com",
  },
  {
    id: 12,
    name: "Animal Control & Welfare",
    description: "Stray animal management and welfare services.",
    issues: "Stray Dogs, Injured Animals",
    contact: "animalcare@civicseva.com",
  },
  {
    id: 13,
    name: "Disaster Management Department",
    description: "Handles floods, landslides, and emergency response.",
    issues: "Flooding, Landslides, Emergency Rescue",
    contact: "disaster@civicseva.com",
  },
  {
    id: 14,
    name: "Encroachment Control Department",
    description: "Removal of illegal structures and encroachments.",
    issues: "Illegal Shops, Footpath Encroachment",
    contact: "encroachment@civicseva.com",
  },
  {
    id: 15,
    name: "Municipal Administration",
    description: "General civic administration and coordination.",
    issues: "General Complaints, Inter-department Issues",
    contact: "admin@civicseva.com",
  },
];


